/**
 * MariaDB Connection Pool
 * 
 * 100% derived from client code analysis.
 * 
 * SCHEMA DESIGN:
 *   user_data uses a single `game_data` JSON column to store ALL 88+ fields
 *   from UserDataParser.saveUserData(). This avoids column mismatch issues
 *   and eliminates the need for ALTER TABLE when adding new fields.
 *   
 *   The enterGame response is generated by generateNewUserData() and
 *   stored directly as JSON. On login, the full JSON is loaded and
 *   returned to the client.
 *   
 *   Scalar columns (user_id, server_id, last_login_time, update_time) 
 *   are kept separate for indexing and querying.
 */

const mariadb = require('mariadb');
const { config } = require('../shared/config');
const logger = require('../shared/utils/logger');

let pool = null;

/**
 * Initialize database connection pool
 */
async function initPool() {
    try {
        pool = mariadb.createPool({
            host: config.database.host,
            port: config.database.port,
            user: config.database.user,
            password: config.database.password,
            database: config.database.database,
            connectionLimit: config.database.connectionLimit,
            connectTimeout: 10000,
            acquireTimeout: 10000,
        });

        // Test connection
        const conn = await pool.getConnection();
        logger.info('DB', 'MariaDB connection successful');
        conn.release();
        return pool;
    } catch (err) {
        logger.error('DB', 'Failed to connect to MariaDB:', err.message);
        throw err;
    }
}

/**
 * Get connection pool
 * @returns {Pool}
 */
function getPool() {
    if (!pool) {
        throw new Error('Database pool not initialized. Call initPool() first.');
    }
    return pool;
}

/**
 * Check if database pool is initialized and ready.
 * Used by main-server health check endpoint:
 *   dbReady: DB.isReady()
 * 
 * @returns {boolean} true if pool is initialized
 */
function isReady() {
    return pool !== null;
}

/**
 * Execute a query
 * @param {string} sql - SQL query
 * @param {array} params - Query parameters
 * @returns {Promise}
 */
async function query(sql, params) {
    const pool = getPool();
    let conn;
    try {
        conn = await pool.getConnection();
        const result = await conn.query(sql, params);
        return result;
    } catch (err) {
        logger.error('DB', 'Query failed: ' + sql, err.message);
        throw err;
    } finally {
        if (conn) conn.release();
    }
}

/**
 * Initialize database schema
 * 
 * Creates tables if they don't exist.
 * Uses DROP + CREATE for user_data to handle schema migration during development.
 * 
 * Source tables:
 *   users       - from UserDataParser e.user (line 77670-77673) + loginGame request (line 77300-77315)
 *   user_data   - from UserDataParser.saveUserData() (line 77641-77724) ALL 88+ fields stored as JSON
 *   user_online - from errorDefine.json code 12: ERROR_USER_LOGIN_BEFORE
 *   login_tokens - from client ts.loginInfo.userInfo.loginToken (line 88719)
 */
async function initSchema() {
    const pool = getPool();
    let conn;

    try {
        conn = await pool.getConnection();
        logger.info('DB', 'Initializing database schema...');

        // Create database if not exists
        await conn.query('CREATE DATABASE IF NOT EXISTS `' + config.database.database + '`');
        await conn.query('USE `' + config.database.database + '`');

        // ============================================
        // users table
        // 
        // 100% from client UserDataParser.saveUserData() (line 77670-77673):
        //   e.user = { _id, _pwd, _nickName, _headImage, _lastLoginTime,
        //               _createTime, _bulletinVersions, _oriServerId, _nickChangeTimes }
        // 
        // 100% from client login request (line 77300-77315):
        //   { type:"User", action:"loginGame", userId, password, fromChannel, 
        //     channelName, headImageUrl, nickName, subChannel, version:"1.0" }
        // 
        // Password is PLAINTEXT (no hash on client side - line 88576-88584)
        // ============================================
        await conn.query(`
            CREATE TABLE IF NOT EXISTS users (
                id INT AUTO_INCREMENT PRIMARY KEY,
                user_id VARCHAR(64) NOT NULL UNIQUE COMMENT 'userId from client - unique login identifier',
                password VARCHAR(128) NOT NULL DEFAULT 'game_origin' COMMENT 'Plaintext password - client sends raw, no hash',
                nick_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '_nickName from UserDataParser',
                head_image VARCHAR(256) NOT NULL DEFAULT '' COMMENT '_headImage from UserDataParser',
                from_channel VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'fromChannel from login request',
                channel_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'channelName from login request',
                sub_channel VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'subChannel from login request',
                ori_server_id INT NOT NULL DEFAULT 0 COMMENT '_oriServerId from UserDataParser',
                nick_change_times INT NOT NULL DEFAULT 0 COMMENT '_nickChangeTimes from UserDataParser',
                last_login_time BIGINT NOT NULL DEFAULT 0 COMMENT '_lastLoginTime from UserDataParser',
                create_time BIGINT NOT NULL DEFAULT 0 COMMENT '_createTime from UserDataParser',
                bulletin_versions TEXT DEFAULT NULL COMMENT '_bulletinVersions from UserDataParser',
                is_new TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'newUser flag - loginSuccessCallBack checks e.newUser (line 77433)',
                INDEX idx_user_id (user_id)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `);

        // ============================================
        // user_data table
        // 
        // Stores per-server user game state as a single JSON blob.
        // ALL 88+ fields from UserDataParser.saveUserData() are stored
        // in the game_data JSON column.
        // 
        // Why JSON column instead of separate columns:
        //   - Client has 88+ fields, many are complex nested objects
        //   - Adding new fields requires NO schema migration
        //   - Eliminates column mismatch bugs entirely
        //   - MariaDB JSON type supports efficient storage and querying
        //   - Game data is always loaded/saved as a complete unit
        // 
        // Source: UserDataParser.saveUserData(e) (line 77641-77724)
        // ============================================

        // FIX 4: Use CREATE TABLE IF NOT EXISTS instead of DROP + CREATE.
        // The original DROP TABLE IF EXISTS destroyed ALL game progress on every restart.
        // This was a dev-mode shortcut that must not remain in production code.
        await conn.query(`
            CREATE TABLE IF NOT EXISTS user_data (
                id INT AUTO_INCREMENT PRIMARY KEY,
                user_id VARCHAR(64) NOT NULL COMMENT 'userId from enterGame request',
                server_id INT NOT NULL DEFAULT 1 COMMENT 'serverId from enterGame request',
                game_data JSON DEFAULT NULL COMMENT 'ALL 88+ fields from UserDataParser.saveUserData() as JSON blob',
                last_login_time BIGINT NOT NULL DEFAULT 0 COMMENT '_lastLoginTime',
                update_time BIGINT NOT NULL DEFAULT 0 COMMENT 'Last data update timestamp',
                UNIQUE KEY uk_user_server (user_id, server_id),
                INDEX idx_user_id (user_id)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `);

        // ============================================
        // user_online table
        // 
        // Tracks which users are online (for ERROR_USER_LOGIN_BEFORE = 12)
        // Client errorDefine.json code 12: ERROR_USER_LOGIN_BEFORE
        // ============================================
        await conn.query(`
            CREATE TABLE IF NOT EXISTS user_online (
                id INT AUTO_INCREMENT PRIMARY KEY,
                user_id VARCHAR(64) NOT NULL,
                server_id INT NOT NULL DEFAULT 1,
                socket_id VARCHAR(128) NOT NULL DEFAULT '',
                login_time BIGINT NOT NULL DEFAULT 0,
                UNIQUE KEY uk_user_server (user_id, server_id)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `);

        // ============================================
        // login_tokens table
        // 
        // Stores active login tokens for session validation.
        // loginToken is generated on loginGame (login server, port 8000)
        // and validated on enterGame (main server, port 8001).
        // 
        // Client: ts.loginInfo.userInfo.loginToken (line 88719)
        // enterGame request: { type:"user", action:"enterGame", loginToken, userId, serverId, ... }
        // ============================================
        await conn.query(`
            CREATE TABLE IF NOT EXISTS login_tokens (
                id INT AUTO_INCREMENT PRIMARY KEY,
                user_id VARCHAR(64) NOT NULL,
                token VARCHAR(256) NOT NULL,
                server_id INT NOT NULL DEFAULT 1,
                created_at BIGINT NOT NULL DEFAULT 0,
                expires_at BIGINT NOT NULL DEFAULT 0,
                used TINYINT(1) NOT NULL DEFAULT 0,
                INDEX idx_token (token),
                INDEX idx_user_id (user_id)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        `);

        logger.info('DB', 'Database schema initialized successfully');
    } catch (err) {
        logger.error('DB', 'Failed to initialize schema:', err.message);
        throw err;
    } finally {
        if (conn) conn.release();
    }
}

/**
 * Gracefully close the connection pool.
 * Called during server shutdown.
 */
async function closePool() {
    if (pool) {
        try {
            await pool.end();
            pool = null;
            logger.info('DB', 'Connection pool closed');
        } catch (err) {
            logger.error('DB', 'Error closing pool:', err.message);
        }
    }
}

module.exports = {
    initPool: initPool,
    getPool: getPool,
    isReady: isReady,
    query: query,
    initSchema: initSchema,
    closePool: closePool,
};
